version: "3"
services:

  node:
    build:
      context: ..
      dockerfile: stack/node/Dockerfile
    image: crhio/node
    ports:
      - "80:3000"
    # env_file: environment.env
    hostname: node
    depends_on:
      - postgres

  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "54320:5432"
    command: postgres -c 'log_statement=all'
